name: Docker Image CI

on:
  workflow_dispatch:
  push:
    branches:
      - master
      - localhost

jobs:

  build:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v4
    - name: Get Versions
      id: version
      run: |
        echo "name=major::$(awk -F, '{print $2}' .tags)" >> $GITHUB_OUTPUT
        echo "name=full::$(awk -F, '{print $1}' .tags)" >> $GITHUB_OUTPUT

    - name: SetUp QEMU
      uses: docker/setup-qemu-action@v3
    - name: Docker Setup Buildx
      uses: docker/setup-buildx-action@v3
    # - name: DockerHub Login
    #   uses: docker/login-action@v3
    #   with:
    #     username: ${{ github.repository_owner }}
    #     password: ${{ secrets.DOCKERHUB_TOKEN }}
    # - name: Github Login
    #   uses: docker/login-action@v3
    #   with:
    #     registry: ghcr.io
    #     username: ${{ github.repository_owner }}
    #     password: ${{ secrets.GH_CAT_TOKEN }}

    - name: Build Docker image
      uses: docker/build-push-action@v5
      with:
        context: .
        file: ./install/Dockerfile
        platforms: linux/amd64,linux/arm/v6,linux/arm/v7,linux/arm64
        push: true
        tags: |
          ${{ github.repository }}:latest
          ${{ github.repository }}:${{ steps.version.outputs.full }}
          ${{ github.repository }}:${{ steps.version.outputs.major }}
          ${{ github.repository_owner }}/${{ github.repository }}:latest
          ${{ github.repository_owner }}/${{ github.repository }}:${{ steps.version.outputs.full }}
          ${{ github.repository_owner }}/${{ github.repository }}:${{ steps.version.outputs.major }}
